"""add others field to users table

Revision ID: a0a6a1edeb67
Revises: bb161eaab271
Create Date: 2025-09-20 23:52:09.015777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0a6a1edeb67'
down_revision: Union[str, Sequence[str], None] = 'bb161eaab271'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('others', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'others')
    # ### end Alembic commands ###
